# feature engineering configuration
feature_engineering:
  data_file: fraud_test3.csv  # Chemin d'accès au fichier de données
  transformations:
    drop_columns:
      - Unnamed: 0
      - cc_num
      - first
      - last
      - street
      - trans_num
      - dob
    datetime_conversion:
      column: trans_date_trans_time
    encode_columns:
      - merchant
      - category
      - gender
      - city
      - state
      - job
    numerical_features:
      - year
      - month
      - day
      - hour

# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
    requirements:
      - pandas
      - xgboost

# pipeline configuration
test_size: 0.2  # Correspond au pourcentage de division des données pour le test
